# **Numpy**

La documentación oficial de Numpy se encuentra publicada en la pagina: https://numpy.org


In [2]:
import numpy as np

# Importacion del paquete de numpay 

## **Array**

Es un objeto que almacena la información de forma oredenada. Se caracteriza por se un tipo de datos idexado que permite acceder a los datos especificos de de forma rapida.


>**Nota:** 
Para Numpy los array solo tienen un unico tipo de dato



In [4]:
lista = [1,2,3,4,5,6,7,8,9,10]
array = np.array(lista)
print(type(array))
print(array)

<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10]


Para acceder a  algun valor del objeto tipo ndarray de numpy se realiza de forma similar a las listas de python considerando que la numeración de posición inicia desde cero (0).

En igual sentido, desde numpy es posible acceder a multiples valores del array por medio del concepto de slicing

In [18]:
valor01 = array[1]
print(f"Suma de valores seleccionados del array = {valor01 + array[5]}")
print(f"Todo el ARray desde la posicion 0 hasta la posicion 5-1, = {array[0:5]}")
print(f"El ejemplo anterior se puede escribir de otra forma con el mismo resultado = {array[:5]}")
print(f"Todo el ARray desde la posicion 2 hasta la posicion 4 (5-1), = {array[2:5]}")
print(f"Todo el ARray desde la posicion 0 hasta la posicion 7 (8-1), saltando de 2 en 2 = {array[:8:2]}")
print(f"Imprime el ultimo elemento del array = {array[-1]}")

Suma de valores seleccionados del array = 8
Todo el ARray desde la posicion 0 hasta la posicion 5-1, = [1 2 3 4 5]
El ejemplo anterior se puede escribir de otra forma con el mismo resultado = [1 2 3 4 5]
Todo el ARray desde la posicion 2 hasta la posicion 4 (5-1), = [3 4 5]
Todo el ARray desde la posicion 0 hasta la posicion 7 (8-1), saltando de 2 en 2 = [1 3 5 7]
Imprime el ultimo elemento del array = 10


### np.arange(): Creando Array con numpy

Numpy tiene incorporada una funcion para crear arays de forma nativa sin tener que recurrir a una lista muy similar a la funcion de python de range

    array = np.arange(inicial, final, step)

In [51]:
array = np.arange(0,10,2)
array

array([0, 2, 4, 6, 8])

### np.zeros()

Crea un array de ceros

Con esta funcion se crean elementos (arreglos, matrices o tensores llenos de ceros)

In [53]:
ceros_dim1 = np.zeros(10)
ceros_dim2 = np.zeros((10,10))
ceros_dim3 = np.zeros((2,2,2))

print(ceros_dim1)
print(ceros_dim2)
print(ceros_dim3)




[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


### np.ones() 

Crea elementos compuestos solo de unos

In [55]:
unos_dim1 = np.ones(10)
unos_dim2 = np.ones((10,10))
unos_dim3 = np.ones((2,2,2))

print(unos_dim1)
print(unos_dim2)
print(unos_dim3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


### np.linspaces

Realiza una distribucion progresiva desde un limite inferior hasta un limite superior


In [57]:
array = np.linspace(0,10,100)

array

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

### np.eye()

Crea una matriz identidad con la dimensión indicada


In [58]:
array = np.eye(5)
array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.empty()

Por medio de la fucion `np.empty()` se crea un array vacio listo para ser poblado con datos

In [25]:
voice_array = np.empty((2,3))
print(voice_array)

#Hay que notar que los resultados de ejecutar a esta función son aproximadamente cero en todas las ubicaciones del array

[[4.65022419e-310 0.00000000e+000 4.65125095e-310]
 [4.65120257e-310 4.65125095e-310 4.05133830e-322]]


### np.ranmdom.rand()

Se crea elementos con numeros aleatorios con las dimensiones indicadas

In [60]:
print(np.random.rand())
print(np.random.rand(4))

0.7812509180079921
[0.37580598 0.13734407 0.64869099 0.8648675 ]


### np.ramdon.randint(inicio, fin, [estructura])

Crea elementos aleatorios de tipo entero


In [62]:
print(np.random.randint(1, 10))
print(np.random.randint(1, 100, (10,10)))


6
[[31 65 33 26  3 29 48 95 11 26]
 [17 61 62 63 48 83 86 96 30 59]
 [51  3 51 72 92 18 10 61 29  1]
 [18 29 64 53  2 31 48 99  8 67]
 [94 92 30 77 26 72 10 41 74 84]
 [67 24 56 31 50 72  2 34 32 22]
 [90 44 74 36 28 55 81  3 77 68]
 [21 67 78 90 64 71 66 82 85 22]
 [92  8  7 25 26  1  7 30 30 21]
 [12 43 99 49 54  7 54 47 71 70]]


### **Matrices**

Para el caso de matrices y elementos multidimencionales es posible juntando distintas listas o arrays dentro de un array



In [7]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Para aceder a una determinada posicion de una matriz se realiza ingresando primero a la posicion de la fila deseada, y luego separado con coma (,) la posicion del elemento dentro de la fila deseado


In [12]:
valor_0_2 = matriz[0,2]
print(f"El valor de la matriz en la posición 0, 2 es = {valor_0_2}")
print(f"El valor de la matriz en la posición 1, 1 es = {matriz[1,1]}")
print(valor_0_2 + matriz[1,1])

el valor de la matriz en la posición 0, 2 es = 3
el valor de la matriz en la posición 1, 1 es = 5
8


## **Tipos de Datos**

La bibliografia oficial se puede consultar en el recurso [data types de Numpy](https://numpy.org/doc/stable/user/basics.types.html)


### dtype

Por medio de la funcion `dtype` es posible identificar el tipo de datos que hay dentor de un array.

por otro lado, cuando se define un array es posible definir desde la defnición misma del array el tipo de datos que debe tenr

In [19]:
array2 = np.array([1,2,3,4,5])
print(array2.dtype)

int64


In [20]:
array3 = np.array([1,2,3,4,5], dtype="float64")
print(array3.dtype)

float64


### np.astype() - Cambiar tipo de datos

Por medio de la funcion astype es posible cambiar los tipos de datos de un array que se tenga

In [23]:
array4  = array.astype(np.float64)
print(f"El array es de tipo: {array.dtype}")
print(array4)
print(array4.dtype)

El array es de tipo: int64
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64


In [26]:
array5 = np.array(['1','2','3','4'])
array6 = array5.astype(np.bool_)
print(array6)
print(f"El tipo de datos de array6 es {array6.dtype}")  

array7 = array5.astype(np.int64)
print(array7)
print(f"El tipo de datos de array7 es {array7.dtype}")  

[ True  True  True  True]
El tipo de datos de array6 es bool
[1 2 3 4]
El tipo de datos de array7 es int64


## **Dimensiones**

Para Numpay existen cuatro tipos de datos segun su dimension, sin embaro permite elementos multi dimensionales de tamaño mayor a 3. Estos elementos o tipos de datos según su dimension son:

|Nombre de dimensión | Valor|
|--------------------|------|
| Escalar | 0 |
| Vector o Array | 1 |
| Matriz | 2 |
| Tensor | > 3 |



### np.ndim: Informa la dimensión

Con la función `.ndim`, es posible conocer la dimensión de un elemento


In [34]:
scalar = np.array([5])
array  =np.array([1,2,3,4])
matriz = np.array([[1,2],[3,4]])
tensor3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(f"El objeto scalar ({scalar}) tiene {scalar.ndim} dimensiones")
print(f"El objeto array ({array}) tiene {array.ndim} dimensiones")
print(f"El objeto matriz: \n {matriz} \ntiene {matriz.ndim} dimensiones")
print(f"El objeto tensor: \n {tensor3} \ntiene {tensor3.ndim} dimensiones")



El objeto scalar ([5]) tiene 1 dimensiones
El objeto array ([1 2 3 4]) tiene 1 dimensiones
El objeto matriz: 
 [[1 2]
 [3 4]] 
tiene 2 dimensiones
El objeto tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
tiene 3 dimensiones


### Determinar las dimensiones de un elementos desde la definición

Por medio de la definición `ndim` dentro de la decalaracion del elemento array puede declararce la dimension desde el inicio




In [35]:
tensor = np.array([1,2,3], ndmin=10)
print(f"El elemento tensor\n {tensor} \ntiene {tensor.ndim} dimensiones")

El elemento tensor
 [[[[[[[[[[1 2 3]]]]]]]]]] 
tiene 10 dimensiones


### np.expand_dims : Expandir dimensiones

Con la funcion `.expan_dims` es posible expandir las dimensiones de un elemento en numpay

In [48]:
elemento = np.array([1,2,3])
expansion = np.expand_dims(elemento, axis=1)
print(f"El elemento \n {elemento} \ntiene {elemento.ndim} dimensiones\n")
print(f"El elemento \n {expansion} \n se le expandio las dimensiones y ahora tiene {expansion.ndim} dimensiones")


El elemento 
 [1 2 3] 
tiene 1 dimensiones

El elemento 
 [[1]
 [2]
 [3]] 
 se le expandio las dimensiones y ahora tiene 2 dimensiones


### np.squeeze: Comprimir las dimensiones

Con la funcion `np.squeeze` se comprime el elemnto a las dimensiones que realmente esten ocupadas

In [49]:
print(f"El elemento \n {expansion} \ntiene {expansion.ndim} dimensiones\n")

compresion  = np.squeeze(expansion)

print(f"El elemento \n {compresion} \n se le comprimio las dimensiones y ahora tiene {compresion.ndim} dimensiones")



El elemento 
 [[1]
 [2]
 [3]] 
tiene 2 dimensiones

El elemento 
 [1 2 3] 
 se le comprimio las dimensiones y ahora tiene 1 dimensiones


## Informacion y cambio de forma de arreglos

### np.shape()

Da informacion para conocer datos del arreglo y las formas en que se puede manipular

In [64]:
array = np.random.randint(1, 10,(5,3))
print(array)
array.shape # se conoce las dimenciones del arreglo

[[4 7 5]
 [9 9 5]
 [9 1 9]]


(3, 3)

### reshape()

Pasa de una estructura con unas dimensiones finales

In [67]:
array.reshape(1,9)


array([[4, 7, 5],
       [9, 9, 5],
       [9, 1, 9]])

In [69]:
np.reshape(array, (1,9), "c")

# Reorganiza el arreglo segun el lenguaje c

array([[4, 7, 5, 9, 9, 5, 9, 1, 9]])

In [70]:
np.reshape(array, (1,9), "f")

# Reorganiza el arreglo segun el lenguaje fortran

array([[4, 9, 9, 7, 9, 1, 5, 5, 9]])

## Funciones principales

La potencia de numpy se destaca en el calculo matematico, En este sentido las principales funciones de numpy estan orientadas a la utilizacion de matematicas y estadistica

In [3]:

array = np.random.randint(1, 20, 10)
matriz = array.reshape(5,2)

print(array)
print(matriz)

[10 17 19  4 16  7  7 10 16  3]
[[10 17]
 [19  4]
 [16  7]
 [ 7 10]
 [16  3]]


### Funciones Matematicas

Para mas informacion consultar [Funciones matematicas](https://numpy.org/doc/stable/reference/routines.math.html)

#### .max() y .min()
retorna valores maximos

In [4]:
# Retorna el valor maximo del elemento
print(array.max())

# Retorna el valor minimo del elemento
print(array.min())

# Retorna los valores maximos en cada columan
print(matriz.max(1))


# Retorna los valores minimos en cada fila
print(matriz.min(0))

19
3
[17 19 16 10 16]
[7 3]


#### np.argmax() y np.argmin()
Retorna las posiciones de las consultas maximos y minimos

In [84]:
print(array, "\n")

# Retorna la posición del maximo del elemento
print(array.argmax(), "\n")

# Retorna la posición del minimo del elemento
print(array.argmin(), "\n")


print(matriz, "\n")
# Retorna la posición de los valores maximos en cada columan
print(matriz.argmax(1), "\n")


# Retorna la posición de los valores minimos en cada fila
print(matriz.argmin(0), "\n")

[ 2  3 12 17 18 16  6  6  7 18] 

4 

0 

[[ 2  3]
 [12 17]
 [18 16]
 [ 6  6]
 [ 7 18]] 

[1 1 0 0 1] 

[0 0] 



#### .ptp()

Muestra la distancia entre el valor mas pequeño y el valos mas alto del elemento

In [87]:
print(array, "\n")

print(array.ptp())

print(f"La funcion ptp calcula: max(array) - min(array) = {array.max()} - {array.min()} = {array.ptp()} ")



[ 2  3 12 17 18 16  6  6  7 18] 

16
La funcion ptp calcula: max(array) - min(array) = 18 - 2 = 16 


### Funciones de Estadistica

#### np.percentile(arr, p)

Calcula el percentil p del arreglo arr





In [16]:
print(array)
print(np.percentile(array,50))

[ 4 17  1 16  8 15  8 12 16  3]
10.0


#### sort()

Al igual que con las listas de python, con sort se ordenan de menor a mayor datos numerios de un arreglo

In [17]:
print(array)
array.sort()
print(array)

[ 4 17  1 16  8 15  8 12 16  3]
[ 1  3  4  8  8 12 15 16 16 17]


#### np.median()

Calcula la mediana de un arreglo

In [19]:
print(np.median(array))

10.0


#### np.std()

Retorna la desviacion estandar de un arreglo


In [21]:
print(np.std(array))

5.692099788303083


#### np.var()

Calcula la varianza de un arreglo

In [22]:
print(np.var(array))

32.4


## **Aritmetica con NumPy**

La aritmetica con NumPy trabaja de elemento en elemento del Array, de tal forma que al aplicar una determinada función al array, la función se aplica a todos los elementos del array.





In [5]:
arr = np.random.randint(1,100,15)
print(arr)

[56 19 35 24 13 48 83 77 50 89 20  2 65 88 32]


### Operaciones con escalares

Las operaciones con escalares propagan el argumento y la operacion descrita a cada elemento del array

#### Suma de una constante

In [6]:
print(arr +5)
print(arr -10)
print(15-arr)

[61 24 40 29 18 53 88 82 55 94 25  7 70 93 37]
[46  9 25 14  3 38 73 67 40 79 10 -8 55 78 22]
[-41  -4 -20  -9   2 -33 -68 -62 -35 -74  -5  13 -50 -73 -17]


#### Multiplicacion de una constante

In [36]:
print(2*arr)
print(1/arr)
print(arr/8)
print(1/8*arr)

[158 132  68 192 150  80 180 160  92  12 136   6  14  58  42]
[0.01265823 0.01515152 0.02941176 0.01041667 0.01333333 0.025
 0.01111111 0.0125     0.02173913 0.16666667 0.01470588 0.33333333
 0.14285714 0.03448276 0.04761905]
[ 9.875  8.25   4.25  12.     9.375  5.    11.25  10.     5.75   0.75
  8.5    0.375  0.875  3.625  2.625]
[ 9.875  8.25   4.25  12.     9.375  5.    11.25  10.     5.75   0.75
  8.5    0.375  0.875  3.625  2.625]


### Operaciones entre Array del mismo tamaño

Cualquier operacion entre arrays del mismo tamaño se aplica de elemento a elemento

In [51]:
matriz1  = np.random.randint(1,10,(3,5) )
matriz2  = np.random.randint(1,10,(3,5) )
print(matriz1)
print("\n")
print(matriz2)

[[9 4 9 3 1]
 [2 9 7 3 6]
 [9 6 2 5 1]]


[[1 1 6 9 8]
 [6 9 2 6 1]
 [9 3 4 1 4]]


#### Suma entre matrices

In [43]:
print(matriz1 + matriz2)

[[ 7  9 10 14  8]
 [13  7 17 14 15]
 [ 9  6  5 12 11]]


#### Producto entre matrices

In [53]:
print(np.matmul(matriz1, matriz2.T))

[[102 127 136]
 [128 131 100]
 [ 80 143 116]]


In [54]:
print(matriz1 @ matriz2.T)

[[102 127 136]
 [128 131 100]
 [ 80 143 116]]


#### Transpuesta de una matriz

In [15]:
A = np.random.randint(1,10,(3,5))
print(A,'\n')
print(A.T)

[[5 4 6 3 2]
 [4 3 2 8 6]
 [4 3 8 3 5]] 

[[5 4 4]
 [4 3 3]
 [6 2 8]
 [3 8 3]
 [2 6 5]]


#### Compáraciones entre matrices

In [46]:
print(matriz1 > matriz2, '\n')

print(matriz1 == matriz2)

[[ True  True  True False False]
 [ True  True  True False  True]
 [False  True False False  True]] 

[[False False False False  True]
 [False False False False False]
 [False False False False False]]


### Concatenación
Permite unir dos elementos de bunoy, sienopre y cuando sean compatibles en sus dimensiones

In [12]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.concatenate((a,b), axis=0)
d = np.concatenate((a,b), axis=1)

print(c)
print("\n")
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


## **Función copy**
 En Python para trabajar con copias de un elemento y desvinculardo de un objeto padre es necesario realizar una copia explicita mediante la función copy


In [24]:
arr = np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

En el siguiente ejemplo se define trozo_arr como una parte de arr, sin embargo trozo_arr sigue vinculado al arreglo padre, para evitar esto, es necesario realizar una copia mediante la función copy

In [29]:
trozo_arr = arr[0:6]
arr_copy = arr.copy()
trozo_copy = arr_copy[0:6]
trozo_arr[:]=0
trozo_copy[:]=1
print(trozo_arr)
print(arr)
print(trozo_copy)
print(arr_copy)

[0 0 0 0 0 0]
[ 0  0  0  0  0  0  6  7  8  9 10]
[1 1 1 1 1 1]
[ 1  1  1  1  1  1  6  7  8  9 10]


La razon de la función copy, es que por medio de esta función realiza una copia del elemento y lo guardo en una posición diferentyes en memoria

## Condiciones de consultas

Por medio de las condiciones definidas en numpy, es posible filtrar los datos de forma tan especifica que los datos deseados cumplan determinadas condiciones.

Para este caso, Numpy va muy por delante del tipico slicing de tal forma que la condición va dentro de los corchetes cuadrados cuando se quiere estrar datos de un elemento de numpy.

In [32]:
arr = np.linspace(1,10,10, dtype="int8")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [35]:
indices_cond = arr >5
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [38]:
arr[(arr>5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [40]:
arr[arr>5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

## **Operaciones**



In [46]:
lista = list(range(0,10))
lista * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
arr = np.arange(0,10)
arr2 = arr.copy()

In [43]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
1/arr

/tmp/ipykernel_1212/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [48]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [49]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])